//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PopcornTime_alpha3_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieDetail
    {
        public int MovieDetailsID { get; set; }
        public string DirectorName { get; set; }
        public Nullable<int> MovieID { get; set; }
        public Nullable<int> TrailerID { get; set; }
    
        public virtual Movy Movy { get; set; }
        public virtual Trailer Trailer { get; set; }
    }
}
